#!/usr/bin/env python3
"""
Create the Fish Finder Outdoors statewide fishing-report search database.

The script combines:
1. The verified public-water and access-point database generated by
   build_idaho_public_fishing_access.py.
2. Current Idaho Fish and Game fishing/stocking updates.
3. Current Idaho reports published by established fishing websites.
4. Public social-media reports intentionally entered in
   data/public_social_reports.csv.

Facebook Groups are not scraped. Meta removed the Groups API and public Page
content requires approved API access. A public Facebook post can still be
included safely by adding its public URL and a short original summary to the
CSV template.

Outputs:
  data/idaho_fishing_report_database.json
  data/idaho_fishing_report_database.js
  data/idaho_fishing_report_database.csv
  data/idaho_fishing_report_summary.csv
  data/fishing_report_build_report.json
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import sys
import time
from collections import defaultdict
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urljoin
from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError

try:
    from bs4 import BeautifulSoup
except ImportError:
    BeautifulSoup = None

COUNTIES = [
    "Ada","Adams","Bannock","Bear Lake","Benewah","Bingham","Blaine","Boise",
    "Bonner","Bonneville","Boundary","Butte","Camas","Canyon","Caribou","Cassia",
    "Clark","Clearwater","Custer","Elmore","Franklin","Fremont","Gem","Gooding",
    "Idaho","Jefferson","Jerome","Kootenai","Latah","Lemhi","Lewis","Lincoln",
    "Madison","Minidoka","Nez Perce","Oneida","Owyhee","Payette","Power",
    "Shoshone","Teton","Twin Falls","Valley","Washington"
]
COUNTY_NUMBER = {county: i + 1 for i, county in enumerate(COUNTIES)}
USER_AGENT = "FishFinderOutdoors-ReportBuilder/1.0 (+https://fishfinderoutdoors.com)"
SPORTSMANS_LIST_URL = (
    "https://fishingreports.sportsmans.com/fishing-report/"
    "page/1/rows/100/keywords/All/site/100/state/ID"
)
IDFG_STOCKING_URL = "https://idfg.idaho.gov/fish/stocking/statewide"
IDFG_FISH_URL = "https://idfg.idaho.gov/fish"
IDFG_ARTICLE_URL = "https://idfg.idaho.gov/article?page={page}"
IDFG_CHINOOK_HARVEST_URL = "https://idfg.idaho.gov/fish/chinook/harvest"
IDFG_STEELHEAD_HARVEST_URL = "https://idfg.idaho.gov/fish/steelhead/harvest"

FISHING_KEYWORDS = (
    "fish", "fishing", "angler", "trout", "bass", "salmon", "steelhead",
    "kokanee", "sturgeon", "walleye", "perch", "crappie", "catfish",
    "stocking", "reservoir", "lake", "river", "creek", "pond"
)
DATE_PATTERNS = (
    "%A, %b %d %Y", "%A, %B %d %Y", "%m/%d/%Y", "%Y-%m-%d",
    "%b %d, %Y", "%B %d, %Y"
)


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def today_iso() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def clean(value: Any) -> str:
    if value is None:
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def norm(value: Any) -> str:
    text = clean(value).lower()
    text = text.replace("&", " and ")
    text = re.sub(r"\b(the|of|at|on|main stem|mainstem)\b", " ", text)
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def compact_norm(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "", clean(value).lower())


def clip(text: str, limit: int = 420) -> str:
    text = clean(text)
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0]
    return cut.rstrip(" ,.;:-") + "…"


def parse_date(value: str) -> str:
    value = clean(value)
    if not value:
        return ""
    value = re.sub(r"(\d+)(st|nd|rd|th)", r"\1", value, flags=re.I)
    for fmt in DATE_PATTERNS:
        try:
            return datetime.strptime(value, fmt).date().isoformat()
        except ValueError:
            pass
    match = re.search(
        r"(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),?\s+"
        r"([A-Za-z]{3,9})\s+(\d{1,2}),?\s+(\d{4})",
        value,
        flags=re.I,
    )
    if match:
        for fmt in ("%A %b %d %Y", "%A %B %d %Y"):
            try:
                return datetime.strptime(" ".join(match.groups()), fmt).date().isoformat()
            except ValueError:
                pass
    match = re.search(r"\b(\d{1,2}/\d{1,2}/\d{4})\b", value)
    if match:
        try:
            return datetime.strptime(match.group(1), "%m/%d/%Y").date().isoformat()
        except ValueError:
            pass
    match = re.search(r"\b(20\d{2}-\d{2}-\d{2})\b", value)
    return match.group(1) if match else ""


def report_age_days(report_date: str) -> int | None:
    try:
        return (datetime.now(timezone.utc).date() - date.fromisoformat(report_date)).days
    except Exception:
        return None


def freshness(report_date: str) -> str:
    age = report_age_days(report_date)
    if age is None:
        return "date_unknown"
    if age <= 14:
        return "very_current"
    if age <= 30:
        return "current"
    if age <= 90:
        return "recent"
    return "stale"


def request_text(url: str, retries: int = 3) -> str:
    last_error: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            req = Request(
                url,
                headers={
                    "User-Agent": USER_AGENT,
                    "Accept": "text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8",
                },
            )
            with urlopen(req, timeout=60) as response:
                charset = response.headers.get_content_charset() or "utf-8"
                return response.read().decode(charset, errors="replace")
        except (HTTPError, URLError, TimeoutError) as exc:
            last_error = exc
            if attempt < retries:
                time.sleep(2 ** attempt)
    raise RuntimeError(f"Unable to retrieve {url}: {last_error}")


def source_id(url: str, report_date: str, title: str) -> str:
    raw = f"{url}|{report_date}|{title}".encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:18]


def make_report(
    *,
    source_type: str,
    source_name: str,
    source_url: str,
    title: str,
    summary: str,
    report_date: str = "",
    water_name: str = "",
    counties: list[str] | None = None,
    rating: str = "",
    species: str = "",
    techniques: str = "",
    access_notes: str = "",
    official: bool = False,
    observed_period: str = "",
    raw_source_reference: str = "",
) -> dict[str, Any]:
    counties = [c for c in (counties or []) if c in COUNTIES]
    report_date = report_date or today_iso()
    return {
        "report_id": source_id(source_url, report_date, title),
        "source_type": source_type,
        "source_name": clean(source_name),
        "source_url": clean(source_url),
        "title": clean(title),
        "summary": clip(summary),
        "report_date": report_date,
        "freshness": freshness(report_date),
        "age_days": report_age_days(report_date),
        "water_name": clean(water_name),
        "counties": counties,
        "rating": clean(rating),
        "species": clean(species),
        "techniques": clean(techniques),
        "access_notes": clean(access_notes),
        "official": bool(official),
        "observed_period": clean(observed_period),
        "raw_source_reference": clean(raw_source_reference),
    }


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def load_access_database(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(
            f"{path} does not exist. Run build_idaho_public_fishing_access.py first."
        )
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("county_count") != 44:
        raise ValueError("Public-access database does not contain all 44 county shells.")
    return payload


def build_water_index(access_db: dict[str, Any], aliases: dict[str, Any]) -> tuple[dict[str, list[dict[str, Any]]], dict[str, set[str]]]:
    index: dict[str, list[dict[str, Any]]] = defaultdict(list)
    counties_by_name: dict[str, set[str]] = defaultdict(set)
    for record in access_db.get("flat_records", []):
        water_name = clean(record.get("water_name"))
        if not water_name:
            continue
        key = norm(water_name)
        index[key].append(record)
        if record.get("county") in COUNTIES:
            counties_by_name[key].add(record["county"])

    for alias, canonical in (aliases.get("aliases") or {}).items():
        canonical_key = norm(canonical)
        if canonical_key in index:
            index[norm(alias)].extend(index[canonical_key])
            counties_by_name[norm(alias)].update(counties_by_name[canonical_key])
    return index, counties_by_name


def best_water_match(name: str, index: dict[str, list[dict[str, Any]]]) -> tuple[str, list[dict[str, Any]], str]:
    key = norm(name)
    if not key:
        return "", [], "no_water_name"
    if key in index:
        canonical = clean(index[key][0].get("water_name"))
        return canonical, index[key], "exact_or_alias"

    # Conservative token matching. Avoid assigning generic names such as
    # "Snake River" to a random county unless the source itself supplies county.
    candidates: list[tuple[float, str, list[dict[str, Any]]]] = []
    query_tokens = set(key.split())
    for candidate_key, records in index.items():
        tokens = set(candidate_key.split())
        if not tokens:
            continue
        overlap = len(query_tokens & tokens)
        union = len(query_tokens | tokens)
        score = overlap / union if union else 0
        if candidate_key in key or key in candidate_key:
            score += 0.35
        if score >= 0.72:
            candidates.append((score, candidate_key, records))
    candidates.sort(key=lambda item: (-item[0], item[1]))
    if len(candidates) == 1 or (len(candidates) > 1 and candidates[0][0] > candidates[1][0] + 0.15):
        records = candidates[0][2]
        return clean(records[0].get("water_name")), records, "conservative_fuzzy"
    return clean(name), [], "unmatched"


def counties_from_records(records: list[dict[str, Any]]) -> list[str]:
    return sorted(
        {r.get("county") for r in records if r.get("county") in COUNTIES},
        key=lambda c: COUNTY_NUMBER[c],
    )


def parse_sportsmans_detail(url: str, html: str) -> dict[str, Any] | None:
    if BeautifulSoup is None:
        raise RuntimeError("beautifulsoup4 is required.")
    soup = BeautifulSoup(html, "html.parser")
    title_node = soup.find("h1")
    title = clean(title_node.get_text(" ", strip=True) if title_node else "")
    if not title or "fishing report" in title.lower():
        # Some pages use the second h1.
        h1s = [clean(x.get_text(" ", strip=True)) for x in soup.find_all("h1")]
        title = next((x for x in h1s if x and "fishing report" not in x.lower()), title)
    page_text = clean(soup.get_text(" ", strip=True))
    date_match = re.search(
        r"(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),?\s+"
        r"(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|"
        r"Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)"
        r"\s+\d{1,2},?\s+20\d{2}",
        page_text,
        flags=re.I,
    )
    report_date = parse_date(date_match.group(0)) if date_match else ""
    rating_match = re.search(r"Rating\s*-\s*([A-Za-z_ ]+)", page_text, flags=re.I)
    rating = clean(rating_match.group(1)).replace("_", " ") if rating_match else ""

    summary = ""
    if date_match:
        after = page_text[date_match.end():]
        after = re.split(
            r"\b(?:Other Fishing Reports|Receive Fishing Report Updates|Subscribe Now|Get special offers)\b",
            after,
            maxsplit=1,
            flags=re.I,
        )[0]
        after = re.sub(rf"^\s*{re.escape(title)}\s*", "", after, flags=re.I)
        summary = clip(after, 420)
    if not summary:
        meta = soup.find("meta", attrs={"name": "description"})
        summary = clip(meta.get("content", "") if meta else "", 420)
    if not title or not summary:
        return None
    return {
        "water_name": title,
        "report_date": report_date or today_iso(),
        "rating": rating,
        "summary": summary,
        "source_url": url,
    }


def collect_sportsmans(index: dict[str, list[dict[str, Any]]], warnings: list[str]) -> list[dict[str, Any]]:
    if BeautifulSoup is None:
        raise RuntimeError("beautifulsoup4 is required.")
    html = request_text(SPORTSMANS_LIST_URL)
    soup = BeautifulSoup(html, "html.parser")
    links: dict[str, str] = {}
    for anchor in soup.find_all("a", href=True):
        href = clean(anchor.get("href"))
        text = clean(anchor.get_text(" ", strip=True))
        if "/fishing-report/" not in href:
            continue
        if "/page/" in href or not text or text.lower() in {"learn more", "view all reports"}:
            continue
        full = urljoin(SPORTSMANS_LIST_URL, href)
        links[full] = text

    reports: list[dict[str, Any]] = []
    for url, link_text in sorted(links.items()):
        try:
            detail = parse_sportsmans_detail(url, request_text(url))
            if not detail:
                continue
            canonical, matches, status = best_water_match(detail["water_name"], index)
            counties = counties_from_records(matches)
            reports.append(make_report(
                source_type="established_fishing_website",
                source_name="Sportsman's Warehouse Fishing Reports",
                source_url=url,
                title=f"{detail['water_name']} fishing report",
                summary=detail["summary"],
                report_date=detail["report_date"],
                water_name=canonical or detail["water_name"],
                counties=counties,
                rating=detail["rating"],
                official=False,
                raw_source_reference=status,
            ))
        except Exception as exc:
            warnings.append(f"Sportsman's detail skipped: {url}: {exc}")
    return reports


def collect_idfg_stocking(index: dict[str, list[dict[str, Any]]], warnings: list[str]) -> list[dict[str, Any]]:
    if BeautifulSoup is None:
        raise RuntimeError("beautifulsoup4 is required.")
    html = request_text(IDFG_STOCKING_URL)
    soup = BeautifulSoup(html, "html.parser")
    reports: list[dict[str, Any]] = []
    seen = set()
    for row in soup.find_all("tr"):
        cells = [clean(cell.get_text(" ", strip=True)) for cell in row.find_all(["td", "th"])]
        if len(cells) < 3:
            continue
        if "body of water" in cells[0].lower():
            continue
        water = cells[0]
        period = cells[1]
        quantity = cells[2]
        if not water or not re.search(r"\d", quantity):
            continue
        key = (water, period, quantity)
        if key in seen:
            continue
        seen.add(key)
        canonical, matches, status = best_water_match(water, index)
        counties = counties_from_records(matches)
        summary = (
            f"Idaho Fish and Game lists {quantity} fish for {water} during "
            f"{period}. Stocking schedules are tentative and can change with "
            "water conditions, angler safety, weather, and staffing."
        )
        reports.append(make_report(
            source_type="official_stocking_update",
            source_name="Idaho Fish and Game",
            source_url=IDFG_STOCKING_URL,
            title=f"{water} stocking update",
            summary=summary,
            report_date=today_iso(),
            water_name=canonical or water,
            counties=counties,
            species="Usually catchable rainbow trout unless the official schedule states otherwise",
            official=True,
            observed_period=period,
            raw_source_reference=status,
        ))
    return reports


def extract_article_cards(html: str, base_url: str) -> list[dict[str, str]]:
    if BeautifulSoup is None:
        raise RuntimeError("beautifulsoup4 is required.")
    soup = BeautifulSoup(html, "html.parser")
    cards = []
    seen = set()
    for anchor in soup.find_all("a", href=True):
        title = clean(anchor.get_text(" ", strip=True))
        href = clean(anchor.get("href"))
        if not title or len(title) < 15:
            continue
        if not any(keyword in title.lower() for keyword in FISHING_KEYWORDS):
            continue
        if "/article/" not in href and "/press/" not in href:
            continue
        url = urljoin(base_url, href)
        if url in seen:
            continue
        seen.add(url)
        parent = anchor.find_parent(["article", "div", "li"])
        surrounding = clean(parent.get_text(" ", strip=True) if parent else title)
        cards.append({"title": title, "url": url, "surrounding": surrounding})
    return cards


def collect_idfg_articles(index: dict[str, list[dict[str, Any]]], warnings: list[str], pages: int = 6) -> list[dict[str, Any]]:
    cards: dict[str, dict[str, str]] = {}
    urls = [IDFG_FISH_URL] + [IDFG_ARTICLE_URL.format(page=i) for i in range(pages)]
    for list_url in urls:
        try:
            for card in extract_article_cards(request_text(list_url), list_url):
                cards[card["url"]] = card
        except Exception as exc:
            warnings.append(f"IDFG article list skipped: {list_url}: {exc}")

    reports: list[dict[str, Any]] = []
    for url, card in sorted(cards.items()):
        try:
            html = request_text(url)
            soup = BeautifulSoup(html, "html.parser")
            page_text = clean(soup.get_text(" ", strip=True))
            title_node = soup.find("h1")
            title = clean(title_node.get_text(" ", strip=True) if title_node else card["title"])
            date_match = re.search(
                r"(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),?\s+"
                r"(January|February|March|April|May|June|July|August|September|October|November|December)"
                r"\s+\d{1,2},?\s+20\d{2}",
                page_text,
                flags=re.I,
            )
            report_date = parse_date(date_match.group(0)) if date_match else parse_date(card["surrounding"])
            body_node = soup.find("main") or soup.find("article")
            body = clean(body_node.get_text(" ", strip=True) if body_node else page_text)
            body = re.sub(rf"^{re.escape(title)}\s*", "", body, flags=re.I)
            summary = clip(body, 420)
            if not any(keyword in (title + " " + summary).lower() for keyword in FISHING_KEYWORDS):
                continue

            # Match all explicit public-water names mentioned in title/body.
            matches_by_water: dict[str, list[dict[str, Any]]] = {}
            searchable = norm(title + " " + summary)
            for water_key, records in index.items():
                if len(water_key) < 5:
                    continue
                if re.search(rf"\b{re.escape(water_key)}\b", searchable):
                    canonical = clean(records[0].get("water_name"))
                    matches_by_water[canonical] = records

            if matches_by_water:
                for water, records in matches_by_water.items():
                    reports.append(make_report(
                        source_type="official_fishing_update",
                        source_name="Idaho Fish and Game",
                        source_url=url,
                        title=title,
                        summary=summary,
                        report_date=report_date or today_iso(),
                        water_name=water,
                        counties=counties_from_records(records),
                        official=True,
                    ))
            else:
                reports.append(make_report(
                    source_type="official_statewide_or_regional_update",
                    source_name="Idaho Fish and Game",
                    source_url=url,
                    title=title,
                    summary=summary,
                    report_date=report_date or today_iso(),
                    official=True,
                ))
        except Exception as exc:
            warnings.append(f"IDFG article skipped: {url}: {exc}")
    return reports


def collect_idfg_harvest_pages(index: dict[str, list[dict[str, Any]]], warnings: list[str]) -> list[dict[str, Any]]:
    reports = []
    for species, url, waters in (
        ("Chinook salmon", IDFG_CHINOOK_HARVEST_URL, ["Snake River", "Clearwater River", "Salmon River"]),
        ("Steelhead", IDFG_STEELHEAD_HARVEST_URL, ["Clearwater River", "Salmon River", "Snake River"]),
    ):
        try:
            html = request_text(url)
            soup = BeautifulSoup(html, "html.parser")
            text = clean(soup.get_text(" ", strip=True))
            date_match = re.search(
                r"(?:Preliminary Harvest Estimates\s*)?"
                r"(January|February|March|April|May|June|July|August|September|October|November|December)"
                r"\s+\d{1,2}(?:\s*-\s*(?:[A-Za-z]+\s+)?\d{1,2})?,?\s+20\d{2}",
                text,
                flags=re.I,
            )
            report_date = today_iso()
            if date_match:
                year_match = re.search(r"20\d{2}", date_match.group(0))
                month_day = re.search(
                    r"(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2})",
                    date_match.group(0),
                    flags=re.I,
                )
                if year_match and month_day:
                    report_date = datetime.strptime(
                        f"{month_day.group(1)} {month_day.group(2)} {year_match.group(0)}",
                        "%B %d %Y",
                    ).date().isoformat()
            summary = clip(text, 420)
            for water in waters:
                canonical, matches, status = best_water_match(water, index)
                reports.append(make_report(
                    source_type="official_harvest_report",
                    source_name="Idaho Fish and Game",
                    source_url=url,
                    title=f"{species} harvest report",
                    summary=summary,
                    report_date=report_date,
                    water_name=canonical or water,
                    counties=counties_from_records(matches),
                    species=species,
                    official=True,
                    raw_source_reference=status,
                ))
        except Exception as exc:
            warnings.append(f"IDFG harvest page skipped: {url}: {exc}")
    return reports


def load_manual_social(path: Path, index: dict[str, list[dict[str, Any]]], warnings: list[str]) -> list[dict[str, Any]]:
    reports = []
    if not path.exists():
        return reports
    with path.open(newline="", encoding="utf-8-sig") as handle:
        for row_number, row in enumerate(csv.DictReader(handle), start=2):
            active = clean(row.get("active")).lower()
            verified = clean(row.get("verified_public_post")).lower()
            if active not in {"1", "true", "yes", "y"}:
                continue
            if verified not in {"1", "true", "yes", "y"}:
                warnings.append(f"Social row {row_number} ignored: verified_public_post is not true.")
                continue
            url = clean(row.get("post_url"))
            if not re.match(r"^https?://", url):
                warnings.append(f"Social row {row_number} ignored: invalid public URL.")
                continue
            water_entered = clean(row.get("water_name"))
            canonical, matches, status = best_water_match(water_entered, index)
            counties = []
            explicit_county = clean(row.get("county")).replace(" County", "")
            if explicit_county in COUNTIES:
                counties = [explicit_county]
            elif matches:
                counties = counties_from_records(matches)
            reports.append(make_report(
                source_type="public_social_post",
                source_name=clean(row.get("source_name")) or "Public social-media post",
                source_url=url,
                title=clean(row.get("title")) or f"{water_entered} community fishing report",
                summary=clean(row.get("summary")),
                report_date=parse_date(clean(row.get("report_date"))) or today_iso(),
                water_name=canonical or water_entered,
                counties=counties,
                rating=clean(row.get("rating")),
                species=clean(row.get("species")),
                techniques=clean(row.get("techniques")),
                access_notes=clean(row.get("access_notes")),
                official=False,
                raw_source_reference=status,
            ))
    return reports


def dedupe_reports(reports: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_key = {}
    for report in reports:
        key = (
            clean(report.get("source_url")),
            clean(report.get("report_date")),
            norm(report.get("water_name")),
            norm(report.get("title")),
        )
        current = by_key.get(key)
        if current is None or len(clean(report.get("summary"))) > len(clean(current.get("summary"))):
            by_key[key] = report
    return sorted(
        by_key.values(),
        key=lambda r: (
            r.get("report_date") or "",
            1 if r.get("official") else 0,
            r.get("source_name") or "",
        ),
        reverse=True,
    )


def report_sort_key(report: dict[str, Any]) -> tuple[Any, ...]:
    return (
        report.get("report_date") or "",
        1 if report.get("official") else 0,
        -int(report.get("age_days") or 999999),
    )


def build_combined_database(access_db: dict[str, Any], reports: list[dict[str, Any]], generated_at: str) -> dict[str, Any]:
    reports_by_water_county: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    statewide_reports = []
    unmatched_reports = []

    for report in reports:
        water = norm(report.get("water_name"))
        counties = report.get("counties") or []
        if water and counties:
            for county in counties:
                reports_by_water_county[(county, water)].append(report)
        elif not water:
            statewide_reports.append(report)
        else:
            unmatched_reports.append(report)

    access_points_by_water_county: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    water_records: dict[tuple[str, str], dict[str, Any]] = {}
    for record in access_db.get("flat_records", []):
        county = record.get("county")
        water_name = clean(record.get("water_name"))
        if county not in COUNTIES or not water_name:
            continue
        key = (county, norm(water_name))
        if record.get("record_kind") == "waterbody":
            existing = water_records.get(key)
            if not existing:
                water_records[key] = {
                    "county_number": COUNTY_NUMBER[county],
                    "county": county,
                    "water_name": water_name,
                    "water_type": record.get("water_type"),
                    "latitude": record.get("latitude"),
                    "longitude": record.get("longitude"),
                    "drainage": record.get("drainage"),
                    "family_fishing_water": record.get("family_fishing_water"),
                    "recommended_fishing_water": record.get("recommended_fishing_water"),
                    "public_access_verification": record.get("public_access_verification"),
                    "official_access_source_url": record.get("official_source_url"),
                    "access_details": record.get("access_details"),
                }
        elif record.get("record_kind") == "access_point":
            access_points_by_water_county[key].append({
                "access_point_name": record.get("access_point_name"),
                "latitude": record.get("latitude"),
                "longitude": record.get("longitude"),
                "directions_url": record.get("directions_url"),
                "amenities": record.get("amenities"),
                "access_flags": record.get("access_flags"),
                "access_details": record.get("access_details"),
                "official_source_url": record.get("official_source_url"),
            })
            # Create a water shell for identified access sites when the hydrography
            # source did not produce a separate waterbody record.
            if key not in water_records:
                water_records[key] = {
                    "county_number": COUNTY_NUMBER[county],
                    "county": county,
                    "water_name": water_name,
                    "water_type": record.get("water_type"),
                    "latitude": record.get("latitude"),
                    "longitude": record.get("longitude"),
                    "drainage": "",
                    "family_fishing_water": False,
                    "recommended_fishing_water": None,
                    "public_access_verification": record.get("public_access_verification"),
                    "official_access_source_url": record.get("official_source_url"),
                    "access_details": "",
                }

    county_blocks = []
    flat_waters = []
    for number, county in enumerate(COUNTIES, start=1):
        waters = []
        for (water_county, water_key), base in sorted(
            water_records.items(),
            key=lambda item: (item[0][0], item[1].get("water_name") or ""),
        ):
            if water_county != county:
                continue
            candidate_reports = list(reports_by_water_county.get((county, water_key), []))
            # Match reports with small naming variations.
            if not candidate_reports:
                for (report_county, report_water), report_list in reports_by_water_county.items():
                    if report_county != county:
                        continue
                    if water_key in report_water or report_water in water_key:
                        candidate_reports.extend(report_list)
            candidate_reports = dedupe_reports(candidate_reports)
            candidate_reports.sort(key=report_sort_key, reverse=True)
            latest = candidate_reports[0] if candidate_reports else None
            status = latest.get("freshness") if latest else "no_recent_public_report_found"
            row = dict(base)
            row.update({
                "access_points": access_points_by_water_county.get((county, water_key), []),
                "access_point_count": len(access_points_by_water_county.get((county, water_key), [])),
                "report_status": status,
                "latest_report": latest,
                "recent_reports": candidate_reports[:10],
                "report_count": len(candidate_reports),
            })
            waters.append(row)
            flat_waters.append(row)

        county_reports = [
            r for r in reports
            if county in (r.get("counties") or [])
        ]
        county_blocks.append({
            "county_number": number,
            "county": county,
            "public_water_count": len(waters),
            "waters_with_reports": sum(1 for w in waters if w["report_count"] > 0),
            "waters_without_reports": sum(1 for w in waters if w["report_count"] == 0),
            "public_access_point_count": sum(w["access_point_count"] for w in waters),
            "county_report_count": len(county_reports),
            "waters": waters,
        })

    return {
        "metadata": {
            "title": "Idaho Public Fishing Access and Current Fishing Reports",
            "version": "2.0",
            "generated_at": generated_at,
            "public_access_only": True,
            "county_order": "1 Ada through 44 Washington",
            "report_policy": (
                "Official reports rank above established fishing websites, which rank "
                "above manually verified public social posts. Every verified public "
                "water remains listed even when no current public report is available."
            ),
            "facebook_policy": (
                "Facebook Groups are not automatically scraped. Only public post URLs "
                "entered in public_social_reports.csv with verified_public_post=true "
                "are included."
            ),
            "freshness_labels": {
                "very_current": "0-14 days old",
                "current": "15-30 days old",
                "recent": "31-90 days old",
                "stale": "More than 90 days old",
                "no_recent_public_report_found": "No matching public report was found"
            },
            "sources": [
                {"name": "Idaho Fish and Game", "type": "official", "url": IDFG_FISH_URL},
                {"name": "IDFG Statewide Fish Stocking Forecast", "type": "official", "url": IDFG_STOCKING_URL},
                {"name": "Sportsman's Warehouse Fishing Reports", "type": "established_fishing_website", "url": SPORTSMANS_LIST_URL},
                {"name": "Manually verified public social posts", "type": "public_social_post", "url": ""}
            ],
        },
        "county_count": 44,
        "public_water_count": len(flat_waters),
        "report_count": len(reports),
        "statewide_reports": statewide_reports[:50],
        "unmatched_reports": unmatched_reports,
        "counties": county_blocks,
        "flat_waters": flat_waters,
        "flat_reports": reports,
    }


def write_outputs(output_dir: Path, db: dict[str, Any], build_report: dict[str, Any]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "idaho_fishing_report_database.json").write_text(
        json.dumps(db, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (output_dir / "idaho_fishing_report_database.js").write_text(
        "/* Automatically generated. Do not hand-edit. */\n"
        "window.IDAHO_FISHING_REPORT_DATABASE = "
        + json.dumps(db, separators=(",", ":"), ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )

    report_fields = [
        "report_id","report_date","freshness","age_days","county_number","county",
        "water_name","source_type","source_name","official","rating","title",
        "summary","species","techniques","access_notes","source_url",
        "observed_period","raw_source_reference"
    ]
    with (output_dir / "idaho_fishing_report_database.csv").open(
        "w", newline="", encoding="utf-8-sig"
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=report_fields)
        writer.writeheader()
        for report in db.get("flat_reports", []):
            counties = report.get("counties") or [""]
            for county in counties:
                writer.writerow({
                    "report_id": report.get("report_id"),
                    "report_date": report.get("report_date"),
                    "freshness": report.get("freshness"),
                    "age_days": report.get("age_days"),
                    "county_number": COUNTY_NUMBER.get(county, ""),
                    "county": county,
                    "water_name": report.get("water_name"),
                    "source_type": report.get("source_type"),
                    "source_name": report.get("source_name"),
                    "official": report.get("official"),
                    "rating": report.get("rating"),
                    "title": report.get("title"),
                    "summary": report.get("summary"),
                    "species": report.get("species"),
                    "techniques": report.get("techniques"),
                    "access_notes": report.get("access_notes"),
                    "source_url": report.get("source_url"),
                    "observed_period": report.get("observed_period"),
                    "raw_source_reference": report.get("raw_source_reference"),
                })

    with (output_dir / "idaho_fishing_report_summary.csv").open(
        "w", newline="", encoding="utf-8-sig"
    ) as handle:
        fields = [
            "county_number","county","public_water_count","waters_with_reports",
            "waters_without_reports","public_access_point_count","county_report_count"
        ]
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for county in db.get("counties", []):
            writer.writerow({field: county.get(field) for field in fields})

    (output_dir / "fishing_report_build_report.json").write_text(
        json.dumps(build_report, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--access-file", default="data/idaho_public_fishing_access.json")
    parser.add_argument("--aliases-file", default="config/water_aliases.json")
    parser.add_argument("--social-file", default="data/public_social_reports.csv")
    parser.add_argument("--output-dir", default="data")
    parser.add_argument("--skip-network", action="store_true")
    args = parser.parse_args()

    generated_at = now_iso()
    output_dir = Path(args.output_dir)
    warnings: list[str] = []
    errors: list[str] = []
    source_counts: dict[str, int] = {}
    try:
        access_db = load_access_database(Path(args.access_file))
        aliases = load_json(Path(args.aliases_file), {"aliases": {}})
        water_index, _ = build_water_index(access_db, aliases)

        reports = []
        social = load_manual_social(Path(args.social_file), water_index, warnings)
        reports.extend(social)
        source_counts["verified_public_social_posts"] = len(social)

        if not args.skip_network:
            collectors = [
                ("sportsmans_reports", lambda: collect_sportsmans(water_index, warnings)),
                ("idfg_stocking_updates", lambda: collect_idfg_stocking(water_index, warnings)),
                ("idfg_fishing_articles", lambda: collect_idfg_articles(water_index, warnings)),
                ("idfg_harvest_reports", lambda: collect_idfg_harvest_pages(water_index, warnings)),
            ]
            for name, collector in collectors:
                try:
                    found = collector()
                    reports.extend(found)
                    source_counts[name] = len(found)
                except Exception as exc:
                    warnings.append(f"{name} collector failed: {exc}")
                    source_counts[name] = 0

        reports = dedupe_reports(reports)
        db = build_combined_database(access_db, reports, generated_at)
        build_report = {
            "generated_at": generated_at,
            "success": True,
            "source_counts": source_counts,
            "public_water_count": db.get("public_water_count"),
            "report_count": db.get("report_count"),
            "unmatched_report_count": len(db.get("unmatched_reports", [])),
            "warnings": warnings,
            "errors": errors,
        }
        write_outputs(output_dir, db, build_report)
        print(json.dumps(build_report, indent=2))
        return 0
    except Exception as exc:
        errors.append(str(exc))
        output_dir.mkdir(parents=True, exist_ok=True)
        build_report = {
            "generated_at": generated_at,
            "success": False,
            "source_counts": source_counts,
            "warnings": warnings,
            "errors": errors,
        }
        (output_dir / "fishing_report_build_report.json").write_text(
            json.dumps(build_report, indent=2), encoding="utf-8"
        )
        print(json.dumps(build_report, indent=2), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
