/* Fish Finder Outdoors managed water directory.
   This file powers both the public search and the private admin dashboard. */
window.FFO_MANAGED_WATER_DIRECTORY = {
  "version": "2026-07-20-managed-directory-v1",
  "updated_at": "2026-07-20",
  "coverage_note": "Waters directly managed by Fish Finder Outdoors. Live external search results are not automatically added to this file.",
  "records": [
    {
      "name": "Napa River",
      "aliases": [
        "napa river",
        "napa river system",
        "napa river california"
      ],
      "display_name": "Napa River, City of Napa and lower Napa County, California",
      "lat": 38.2975,
      "lon": -122.2869,
      "state": "California",
      "county": "Napa",
      "category": "water",
      "type": "river",
      "official_url": "https://wildlife.ca.gov/Fishing-in-the-City/SF/Gofish/Northeast",
      "nearby_towns": [
        "napa",
        "napa california",
        "napa ca",
        "napa county",
        "yountville",
        "american canyon"
      ],
      "nearby_town_label": "Napa",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "California Fish and Wildlife identifies the main Napa River from the City of Napa downstream as a public fishing opportunity. Use designated public riverfront, park, pier, marina, or boat access; many upstream banks and tributaries are private or closed.",
      "public_access_source": "California Department of Fish and Wildlife",
      "directory_id": "ffo-managed-001",
      "managed_source": "Fish Finder Outdoors managed directory"
    },
    {
      "name": "Lake Hennessey",
      "aliases": [
        "lake hennessey",
        "hennessey lake",
        "hennessey reservoir"
      ],
      "display_name": "Lake Hennessey, Napa County, California",
      "lat": 38.513,
      "lon": -122.366,
      "state": "California",
      "county": "Napa",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://wildlife.ca.gov/Fishing-in-the-City/SF/Gofish/Northeast",
      "nearby_towns": [
        "napa",
        "napa california",
        "napa ca",
        "napa county",
        "st helena",
        "saint helena"
      ],
      "nearby_town_label": "Napa",
      "public_access_verified": true,
      "access_status": "restricted",
      "public_access_note": "California Fish and Wildlife lists Lake Hennessey as open to the public, with access or launch fees and boating restrictions. Current launch closures or invasive-species rules must be checked before travel.",
      "public_access_source": "California Department of Fish and Wildlife",
      "directory_id": "ffo-managed-002",
      "managed_source": "Fish Finder Outdoors managed directory"
    },
    {
      "name": "Lake Berryessa",
      "aliases": [
        "lake berryessa",
        "berryessa lake",
        "berryessa reservoir"
      ],
      "display_name": "Lake Berryessa, Napa County, California",
      "lat": 38.513,
      "lon": -122.104,
      "state": "California",
      "county": "Napa",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://wildlife.ca.gov/Fishing-in-the-City/SF/Gofish/Northeast",
      "nearby_towns": [
        "napa",
        "napa california",
        "napa ca",
        "napa county",
        "winters",
        "st helena",
        "saint helena"
      ],
      "nearby_town_label": "Napa",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "California Fish and Wildlife lists Lake Berryessa as open to the public. Some resort, launch, parking, or inspection fees and restrictions may apply.",
      "public_access_source": "California Department of Fish and Wildlife",
      "directory_id": "ffo-managed-003",
      "managed_source": "Fish Finder Outdoors managed directory"
    },
    {
      "name": "Bannock Reservoir",
      "aliases": [
        "bannock reservoir",
        "bannock res",
        "bannock res.",
        "bannock lake",
        "portneuf wellness complex pond",
        "portneuf wellness pond",
        "portneuf wellness lake",
        "wellness complex pond",
        "wellness reservoir",
        "wellness pond",
        "wellness lake"
      ],
      "display_name": "Bannock Reservoir (Portneuf Wellness Complex Pond), Bannock County, Idaho",
      "lat": 42.91859,
      "lon": -112.43174,
      "state": "Idaho",
      "county": "Bannock",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1124345429181",
      "nearby_towns": [
        "pocatello",
        "pocatello idaho",
        "pocatello id",
        "chubbuck",
        "chubbuck idaho",
        "bannock county"
      ],
      "nearby_town_label": "Pocatello",
      "public_access_verified": true,
      "public_access_note": "Public family fishing water inside the Portneuf Wellness Complex. Multiple docks and accessible shoreline are available.",
      "public_access_source": "Idaho Fish and Game Fishing Planner",
      "directory_id": "ffo-managed-004",
      "managed_source": "Fish Finder Outdoors managed directory",
      "access_status": "open"
    },
    {
      "name": "Edson Fichter Pond",
      "aliases": [
        "edson fichter pond",
        "edson fichter reservoir",
        "edson fichter res",
        "edson fichter res.",
        "edson fichter lake",
        "edson fichter fishing pond",
        "edson fitcher pond",
        "edson fitcher reservoir",
        "edson fitcher res",
        "edson fitcher res.",
        "edson fitcher lake",
        "edson fisher pond",
        "fichter pond",
        "fitcher pond",
        "edson pond"
      ],
      "display_name": "Edson Fichter Pond, Edson Fichter Nature Area, Pocatello, Idaho",
      "lat": 42.82186,
      "lon": -112.40316,
      "state": "Idaho",
      "county": "Bannock",
      "category": "water",
      "type": "pond",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingPlanner/water/1124032428216",
      "nearby_towns": [
        "pocatello",
        "pocatello idaho",
        "pocatello id",
        "chubbuck",
        "chubbuck idaho",
        "bannock county"
      ],
      "nearby_town_label": "Pocatello",
      "public_access_verified": true,
      "public_access_note": "Public family fishing water at Edson Fichter Nature Area. Docks, trails and accessible shoreline are available.",
      "public_access_source": "Idaho Fish and Game Fishing Planner",
      "directory_id": "ffo-managed-005",
      "managed_source": "Fish Finder Outdoors managed directory",
      "access_status": "open"
    },
    {
      "name": "Blackfoot Reservoir",
      "aliases": [
        "blackfoot reservoir",
        "blackfoot lake",
        "blackfoot reservoir idaho"
      ],
      "display_name": "Blackfoot Reservoir, Bingham and Caribou Counties, Idaho",
      "lat": 42.914614,
      "lon": -111.609092,
      "state": "Idaho",
      "county": "Bingham / Caribou",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1115975428895",
      "directory_id": "ffo-managed-006",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Devil Creek Reservoir",
      "aliases": [
        "devil creek reservoir",
        "devils creek reservoir",
        "devil's creek reservoir",
        "devil creek lake"
      ],
      "display_name": "Devil Creek Reservoir, Oneida County, Idaho \u2014 near Malad City",
      "lat": 42.32,
      "lon": -112.73,
      "state": "Idaho",
      "county": "Oneida",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1122052422984",
      "directory_id": "ffo-managed-007",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Chesterfield Reservoir",
      "aliases": [
        "chesterfield reservoir",
        "portneuf reservoir",
        "chesterfield lake"
      ],
      "display_name": "Chesterfield Reservoir (Portneuf Reservoir), Caribou County, Idaho",
      "lat": 42.897585,
      "lon": -111.967311,
      "state": "Idaho",
      "county": "Caribou",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1119715429000",
      "directory_id": "ffo-managed-008",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Daniels Reservoir",
      "aliases": [
        "daniels reservoir",
        "daniel reservoir",
        "daniels lake"
      ],
      "display_name": "Daniels Reservoir, Oneida County, Idaho \u2014 northwest of Malad City",
      "lat": 42.35529,
      "lon": -112.445543,
      "state": "Idaho",
      "county": "Oneida",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1124478423573",
      "directory_id": "ffo-managed-009",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Alexander Reservoir",
      "aliases": [
        "alexander reservoir",
        "alexander lake",
        "soda springs reservoir"
      ],
      "display_name": "Alexander Reservoir, Caribou County, Idaho \u2014 Soda Springs",
      "lat": 42.654,
      "lon": -111.636857,
      "state": "Idaho",
      "county": "Caribou",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1116455426547",
      "directory_id": "ffo-managed-010",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Oneida Narrows Reservoir",
      "aliases": [
        "oneida narrows reservoir",
        "oneida reservoir",
        "oneida narrows",
        "oneida lake"
      ],
      "display_name": "Oneida Narrows Reservoir, Franklin County, Idaho",
      "lat": 42.29352,
      "lon": -111.728978,
      "state": "Idaho",
      "county": "Franklin",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1117295422907",
      "directory_id": "ffo-managed-011",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Glendale Reservoir",
      "aliases": [
        "glendale reservoir",
        "glendale lake",
        "glendale reservoir idaho"
      ],
      "display_name": "Glendale Reservoir, Franklin County, Idaho \u2014 near Preston",
      "lat": 42.134223,
      "lon": -111.797581,
      "state": "Idaho",
      "county": "Franklin",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1117964421349",
      "directory_id": "ffo-managed-012",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Treasureton Reservoir",
      "aliases": [
        "treasureton reservoir",
        "treasureton lake"
      ],
      "display_name": "Treasureton Reservoir, Franklin County, Idaho",
      "lat": 42.233811,
      "lon": -111.861897,
      "state": "Idaho",
      "county": "Franklin",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/",
      "directory_id": "ffo-managed-013",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Twentyfour Mile Reservoir",
      "aliases": [
        "twentyfour mile reservoir",
        "twenty four mile reservoir",
        "24 mile reservoir",
        "twenty-four mile reservoir"
      ],
      "display_name": "Twentyfour Mile Reservoir, Caribou County, Idaho",
      "lat": 42.9062,
      "lon": -111.889,
      "state": "Idaho",
      "county": "Caribou",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1118897429069",
      "directory_id": "ffo-managed-014",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "Ririe Reservoir",
      "aliases": [
        "ririe reservoir",
        "ririe lake",
        "blacktail reservoir",
        "blacktail park reservoir"
      ],
      "display_name": "Ririe Reservoir, Bonneville County, Idaho",
      "lat": 43.520199,
      "lon": -111.720511,
      "state": "Idaho",
      "county": "Bonneville",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingplanner/water/1117154435340",
      "directory_id": "ffo-managed-015",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    },
    {
      "name": "American Falls Reservoir",
      "aliases": [
        "american falls reservoir",
        "american falls lake",
        "willow bay reservoir"
      ],
      "display_name": "American Falls Reservoir, Power and Bingham Counties, Idaho",
      "lat": 42.783,
      "lon": -112.879,
      "state": "Idaho",
      "county": "Power / Bingham",
      "category": "water",
      "type": "reservoir",
      "official_url": "https://idfg.idaho.gov/ifwis/fishingPlanner/water/1127315429370",
      "directory_id": "ffo-managed-016",
      "nearby_towns": [],
      "managed_source": "Fish Finder Outdoors managed directory",
      "public_access_verified": true,
      "access_status": "open",
      "public_access_note": "Public fishing access is documented through the listed state fishing-agency record. Verify current rules and access before traveling.",
      "public_access_source": "State fishing agency"
    }
  ]
};
