/* Automatic source-monitor status used by the public site and review dashboard. */
window.FFO_UPDATE_STATUS = {
  "last_run": "2026-07-20T19:16:18Z",
  "mode": "live",
  "reports_total": 45,
  "unique_sources": 34,
  "official_directories_total": 9,
  "official_directories_unreachable": 0,
  "freshness": {
    "current": 30,
    "aging": 14,
    "stale": 1,
    "unknown": 0
  },
  "changed_reports": 0,
  "review_required": 0,
  "unreachable_sources": 0,
  "sources": [
    {
      "source_url": "https://cpw.state.co.us/fishing",
      "source_type": "official_state_directory",
      "state": "Colorado",
      "agency": "Colorado official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Fishing | Colorado Parks and Wildlife",
      "last_modified": "Mon, 20 Jul 2026 18:51:20 GMT",
      "page_published": null,
      "page_modified": "2026-07-15T15:48:48-0600",
      "elapsed_ms": 335,
      "error": null
    },
    {
      "source_url": "https://dwrapps.utah.gov/fishing/",
      "source_type": "official_state_directory",
      "state": "Utah",
      "agency": "Utah official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Fish Utah -- Division of Wildlife Resources",
      "last_modified": null,
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 505,
      "error": null
    },
    {
      "source_url": "https://idfg.idaho.gov/article/2026-dworshak-reservoir-kokanee-update",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Idaho Fish and Game",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "2026 Dworshak Reservoir Kokanee Update | Idaho Fish and Game",
      "last_modified": "Mon, 20 Jul 2026 19:16:19 GMT",
      "page_published": "2026-06-25T09:49:24-06:00",
      "page_modified": null,
      "elapsed_ms": 1884,
      "error": null
    },
    {
      "source_url": "https://idfg.idaho.gov/article/2026-dworshak-reservoir-smallmouth-bass-update",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Idaho Fish and Game",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "2026 Dworshak Reservoir Smallmouth Bass Update | Idaho Fish and Game",
      "last_modified": "Mon, 20 Jul 2026 19:16:22 GMT",
      "page_published": "2026-06-25T10:09:36-06:00",
      "page_modified": null,
      "elapsed_ms": 1787,
      "error": null
    },
    {
      "source_url": "https://idfg.idaho.gov/article/july-14-2026-south-fork-salmon-river-chinook-update",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Idaho Fish and Game",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "July 14, 2026 South Fork Salmon River Chinook Update | Idaho Fish and Game",
      "last_modified": "Mon, 20 Jul 2026 19:16:24 GMT",
      "page_published": "2026-07-14T12:52:13-06:00",
      "page_modified": null,
      "elapsed_ms": 1971,
      "error": null
    },
    {
      "source_url": "https://idfg.idaho.gov/article/managing-moose-creek-reservoir-making-fishing-better",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Idaho Fish and Game",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Managing Moose Creek Reservoir: Making Fishing Better | Idaho Fish and Game",
      "last_modified": "Mon, 20 Jul 2026 19:16:26 GMT",
      "page_published": "2026-06-26T10:20:19-06:00",
      "page_modified": null,
      "elapsed_ms": 1574,
      "error": null
    },
    {
      "source_url": "https://idfg.idaho.gov/fish/chinook/harvest",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Idaho Fish and Game",
      "report_count": 4,
      "status": "ok",
      "http_status": 200,
      "title": "Chinook Harvest Report | Idaho Fish and Game",
      "last_modified": "Mon, 20 Jul 2026 19:12:51 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 494,
      "error": null
    },
    {
      "source_url": "https://idfg.idaho.gov/ifwis/fishingPlanner/",
      "source_type": "official_state_directory",
      "state": "Idaho",
      "agency": "Idaho official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Idaho Fishing Planner",
      "last_modified": "Mon, 20 Jul 2026 17:13:06 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 321,
      "error": null
    },
    {
      "source_url": "https://myfwp.mt.gov/fishMT/explore",
      "source_type": "official_state_directory",
      "state": "Montana",
      "agency": "Montana official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "FISHMT :: Waterbody Search",
      "last_modified": null,
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 1758,
      "error": null
    },
    {
      "source_url": "https://myodfw.com/fishing",
      "source_type": "official_state_directory",
      "state": "Oregon",
      "agency": "Oregon official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Fishing | Oregon Department of Fish & Wildlife",
      "last_modified": "Mon, 20 Jul 2026 19:16:32 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 444,
      "error": null
    },
    {
      "source_url": "https://myodfw.com/recreation-report/fishing-report/marine-zone",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Oregon Department of Fish and Wildlife",
      "report_count": 11,
      "status": "ok",
      "http_status": 200,
      "title": "Fishing Report - Marine Zone | Oregon Department of Fish & Wildlife",
      "last_modified": "Mon, 20 Jul 2026 19:16:32 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 201,
      "error": null
    },
    {
      "source_url": "https://wdfw.wa.gov/fishing/locations",
      "source_type": "official_state_directory",
      "state": "Washington",
      "agency": "Washington official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Places to go fishing | Washington Department of Fish & Wildlife",
      "last_modified": "Mon, 20 Jul 2026 19:15:18 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 212,
      "error": null
    },
    {
      "source_url": "https://wdfw.wa.gov/fishing/reports/creel/puget",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Washington Department of Fish and Wildlife",
      "report_count": 3,
      "status": "ok",
      "http_status": 200,
      "title": "Puget Sound creel reports | Washington Department of Fish & Wildlife",
      "last_modified": "Mon, 20 Jul 2026 18:22:06 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 149,
      "error": null
    },
    {
      "source_url": "https://wdfw.wa.gov/fishing/reports/creel/puget-annual",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Washington Department of Fish and Wildlife",
      "report_count": 3,
      "status": "ok",
      "http_status": 200,
      "title": "Puget Sound creel reports by year | Washington Department of Fish & Wildlife",
      "last_modified": "Mon, 20 Jul 2026 19:16:34 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 871,
      "error": null
    },
    {
      "source_url": "https://wdfw.wa.gov/fishing/reports/creel/puget?catch_area=05&ramp=&sample_date=3",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Washington Department of Fish and Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Puget Sound creel reports | Washington Department of Fish & Wildlife",
      "last_modified": "Mon, 20 Jul 2026 19:16:35 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 985,
      "error": null
    },
    {
      "source_url": "https://wdfw.wa.gov/fishing/reports/creel/puget?page=1",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Washington Department of Fish and Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Puget Sound creel reports | Washington Department of Fish & Wildlife",
      "last_modified": "Mon, 20 Jul 2026 18:24:19 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 175,
      "error": null
    },
    {
      "source_url": "https://wgfd.wyo.gov/fishing-boating/places-fish-wyoming",
      "source_type": "official_state_directory",
      "state": "Wyoming",
      "agency": "Wyoming official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Places to fish in Wyoming | Wyoming Game & Fish Department",
      "last_modified": "Mon, 20 Jul 2026 19:02:22 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 197,
      "error": null
    },
    {
      "source_url": "https://wgfd.wyo.gov/news-events/anglers-remove-over-1200-small-lake-trout-flaming-gorge-through-angler-harvest-program",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Wyoming Game and Fish Department",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Anglers remove over 1,200 small lake trout from Flaming Gorge through the Angler Harvest Program | Wyoming Game & Fish Department",
      "last_modified": "Mon, 20 Jul 2026 19:16:37 GMT",
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 1616,
      "error": null
    },
    {
      "source_url": "https://wildlife.ca.gov/Fishing/Guide",
      "source_type": "official_state_directory",
      "state": "California",
      "agency": "California official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Fishing Guide",
      "last_modified": null,
      "page_published": null,
      "page_modified": null,
      "elapsed_ms": 708,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/blog/fishing-report-7-15-26/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 4,
      "status": "ok",
      "http_status": 200,
      "title": "Fishing Report: 07/15/2026 - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:50:14 GMT",
      "page_published": "2026-07-15T08:22:00+00:00",
      "page_modified": "2026-07-15T17:27:15+00:00",
      "elapsed_ms": 701,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/get-outside/fishing-stocking-reports/database/",
      "source_type": "official_state_directory",
      "state": "Nevada",
      "agency": "Nevada official fishing directory",
      "report_count": 0,
      "status": "ok",
      "http_status": 200,
      "title": "Fishing & Stocking Reports - Nevada Fishing",
      "last_modified": "Fri, 17 Jul 2026 19:26:50 GMT",
      "page_published": "2021-11-02T16:07:05+00:00",
      "page_modified": "2025-09-26T12:38:38+00:00",
      "elapsed_ms": 571,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/angel-lake/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Angel Lake - Nevada Department of Wildlife",
      "last_modified": "Mon, 20 Jul 2026 18:08:26 GMT",
      "page_published": "2021-10-31T18:42:59+00:00",
      "page_modified": "2026-07-20T17:24:45+00:00",
      "elapsed_ms": 533,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/eagle-valley-reservoir/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Eagle Valley Reservoir - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:54:21 GMT",
      "page_published": "2021-10-31T18:43:02+00:00",
      "page_modified": "2026-06-03T15:47:05+00:00",
      "elapsed_ms": 567,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/james-kinney-pond/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "James Kinney Pond - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:39:52 GMT",
      "page_published": "2021-10-31T18:43:04+00:00",
      "page_modified": "2026-07-13T19:41:04+00:00",
      "elapsed_ms": 501,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/kiley-ranch-pond/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Battle Born Pond - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 20:23:14 GMT",
      "page_published": "2023-05-30T16:47:28+00:00",
      "page_modified": "2026-05-20T20:18:30+00:00",
      "elapsed_ms": 516,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/lake-tahoe-zephyr-cove/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Lake Tahoe - Zephyr Cove - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 20:04:21 GMT",
      "page_published": "2022-06-23T21:40:11+00:00",
      "page_modified": "2026-06-23T22:25:18+00:00",
      "elapsed_ms": 512,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/lake-tahoe/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Lake Tahoe - Sand Harbor - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 22:11:46 GMT",
      "page_published": "2021-10-31T18:43:04+00:00",
      "page_modified": "2026-07-10T21:37:55+00:00",
      "elapsed_ms": 518,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/marilyns-pond/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Marilyn's Pond - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:18:32 GMT",
      "page_published": "2021-10-31T18:43:04+00:00",
      "page_modified": "2026-07-14T21:40:50+00:00",
      "elapsed_ms": 550,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/mason-valley-hatchery-outponds/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Mason Valley Hatchery Outponds - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 20:10:53 GMT",
      "page_published": "2022-07-08T23:17:05+00:00",
      "page_modified": "2026-04-17T18:18:10+00:00",
      "elapsed_ms": 506,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/ruby-lake-collection-ditch/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Ruby Lake NWR - Collection Ditch - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 20:14:06 GMT",
      "page_published": "2021-10-31T18:43:01+00:00",
      "page_modified": "2026-07-15T16:22:28+00:00",
      "elapsed_ms": 506,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/ruby-lake/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Ruby Lake NWR - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:20:05 GMT",
      "page_published": "2021-10-31T18:43:01+00:00",
      "page_modified": "2026-07-15T16:15:06+00:00",
      "elapsed_ms": 509,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/south-fork-reservoir/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "South Fork Reservoir - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:52:45 GMT",
      "page_published": "2021-10-31T18:43:01+00:00",
      "page_modified": "2026-07-15T17:22:29+00:00",
      "elapsed_ms": 572,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/truckee-river/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Truckee River - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:23:58 GMT",
      "page_published": "2021-10-31T18:43:05+00:00",
      "page_modified": "2026-06-29T20:07:15+00:00",
      "elapsed_ms": 498,
      "error": null
    },
    {
      "source_url": "https://www.ndow.org/waters/wildhorse-reservoir/",
      "source_type": "fishing_report_source",
      "state": null,
      "agency": "Nevada Department of Wildlife",
      "report_count": 1,
      "status": "ok",
      "http_status": 200,
      "title": "Wildhorse Reservoir - Nevada Department of Wildlife",
      "last_modified": "Fri, 17 Jul 2026 19:23:14 GMT",
      "page_published": "2021-10-31T18:43:01+00:00",
      "page_modified": "2026-07-15T20:13:32+00:00",
      "elapsed_ms": 501,
      "error": null
    }
  ],
  "note": "Source changes are flagged for review. Catch numbers are never automatically rewritten from unstructured webpage text."
};
